const body = [
  'Names|Account Setup BCEiD',
  'Names|Act Interpretations',
  'Names|Business Number Query',
  'Names|DBA',
  'Names|Account Setup BCSC',
  'Names|Feedback/Complaint',
  'Names|General Information',
  'Names|Hang Up/ Lost Call',
  'Names|Information Pkgs/ where to Find Info on W',
  'Names|NWPT',
  'Names|Online Filing Assistance',
  'Names|Priority Explanation',
  'Names|Receipt of Documents in BCRS',
  'Names|Referrals to Other Business Agencies',
  'Names|Referrals to Other Business Agencies',
  'Names|Reprints and Sending Documents',
  'Names|Restorations/ Info Pkg',
  'Names|Search or Product',
  'Names|Web Page/ System Issue',
  'Names|Access Codes/ Passwords/ Customer Profiles CSC',
  "Names|Annual Reports/ Change of Director's/Address CSC",
  'Names|Corrections/Amendments CSC',
  'Names|Dissolution/Info Pkg CSC',
  'Names|Incorporations/Amalg/Continuations/Xpro CSC',
  'Names|Close LOB Window',
  'Names|Consent Inquiry',
  'Names|Email Names/Registration',
  'Names|Name Appeal',
  'Names|Name Application',
  'Names|Name Criteria',
  'Names|Name Request Change',
  'Names|Name request Status',
];
